/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NurtureIndexRouteImport } from './routes/nurture.index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as NurtureThreadIdRouteImport } from './routes/nurture.$threadId'
import { Route as LearnArticleIdRouteImport } from './routes/learn.$articleId'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NurtureIndexRoute = NurtureIndexRouteImport.update({
  id: '/nurture/',
  path: '/nurture/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const NurtureThreadIdRoute = NurtureThreadIdRouteImport.update({
  id: '/nurture/$threadId',
  path: '/nurture/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnArticleIdRoute = LearnArticleIdRouteImport.update({
  id: '/learn/$articleId',
  path: '/learn/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/chat': typeof ChatRoute
  '/get-started': typeof GetStartedRoute
  '/growth': typeof GrowthRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/track': typeof TrackRoute
  '/api/chat': typeof ApiChatRoute
  '/learn/$articleId': typeof LearnArticleIdRoute
  '/nurture/$threadId': typeof NurtureThreadIdRoute
  '/learn/': typeof LearnIndexRoute
  '/nurture/': typeof NurtureIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/chat': typeof ChatRoute
  '/get-started': typeof GetStartedRoute
  '/growth': typeof GrowthRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/track': typeof TrackRoute
  '/api/chat': typeof ApiChatRoute
  '/learn/$articleId': typeof LearnArticleIdRoute
  '/nurture/$threadId': typeof NurtureThreadIdRoute
  '/learn': typeof LearnIndexRoute
  '/nurture': typeof NurtureIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/chat': typeof ChatRoute
  '/get-started': typeof GetStartedRoute
  '/growth': typeof GrowthRoute
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/track': typeof TrackRoute
  '/api/chat': typeof ApiChatRoute
  '/learn/$articleId': typeof LearnArticleIdRoute
  '/nurture/$threadId': typeof NurtureThreadIdRoute
  '/learn/': typeof LearnIndexRoute
  '/nurture/': typeof NurtureIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/chat'
    | '/get-started'
    | '/growth'
    | '/home'
    | '/journey'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/shop'
    | '/support'
    | '/track'
    | '/api/chat'
    | '/learn/$articleId'
    | '/nurture/$threadId'
    | '/learn/'
    | '/nurture/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/chat'
    | '/get-started'
    | '/growth'
    | '/home'
    | '/journey'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/shop'
    | '/support'
    | '/track'
    | '/api/chat'
    | '/learn/$articleId'
    | '/nurture/$threadId'
    | '/learn'
    | '/nurture'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/chat'
    | '/get-started'
    | '/growth'
    | '/home'
    | '/journey'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/shop'
    | '/support'
    | '/track'
    | '/api/chat'
    | '/learn/$articleId'
    | '/nurture/$threadId'
    | '/learn/'
    | '/nurture/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ChatRoute: typeof ChatRoute
  GetStartedRoute: typeof GetStartedRoute
  GrowthRoute: typeof GrowthRoute
  HomeRoute: typeof HomeRoute
  JourneyRoute: typeof JourneyRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ShopRoute: typeof ShopRoute
  SupportRoute: typeof SupportRoute
  TrackRoute: typeof TrackRoute
  ApiChatRoute: typeof ApiChatRoute
  LearnArticleIdRoute: typeof LearnArticleIdRoute
  NurtureThreadIdRoute: typeof NurtureThreadIdRoute
  LearnIndexRoute: typeof LearnIndexRoute
  NurtureIndexRoute: typeof NurtureIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurture/': {
      id: '/nurture/'
      path: '/nurture'
      fullPath: '/nurture/'
      preLoaderRoute: typeof NurtureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurture/$threadId': {
      id: '/nurture/$threadId'
      path: '/nurture/$threadId'
      fullPath: '/nurture/$threadId'
      preLoaderRoute: typeof NurtureThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$articleId': {
      id: '/learn/$articleId'
      path: '/learn/$articleId'
      fullPath: '/learn/$articleId'
      preLoaderRoute: typeof LearnArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ChatRoute: ChatRoute,
  GetStartedRoute: GetStartedRoute,
  GrowthRoute: GrowthRoute,
  HomeRoute: HomeRoute,
  JourneyRoute: JourneyRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ShopRoute: ShopRoute,
  SupportRoute: SupportRoute,
  TrackRoute: TrackRoute,
  ApiChatRoute: ApiChatRoute,
  LearnArticleIdRoute: LearnArticleIdRoute,
  NurtureThreadIdRoute: NurtureThreadIdRoute,
  LearnIndexRoute: LearnIndexRoute,
  NurtureIndexRoute: NurtureIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
